# Generated by Django 4.1.4 on 2022-12-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0002_alter_tinymessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinymessage',
            options={'ordering': ['-id']},
        ),
    ]
